name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'log4jecr'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'abhiacreastus.azurecr.io/log4jecr:${{ github.sha }}'
